---
version: "3.9"
services:
  webserver:
    image: vinodchenga/javawebapp:9
    ports:
      - target: 8080
        published: 8082
        protocol: tcp
        mode: host
    networks:
      - webserver-net
  dbserver:
    image: mysql:5.6
    ports:
      - target: 3306
        published: 8083
        protocol: tcp
        mode: host
    networks:
      - webserver-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=javawebappdb
networks:
  webserver-net:
    driver: bridge
    ipam:
      driver: default